### ISSUE TITLE
Enable running on arm

### ISSUE THREAD

**Issue by arj03** [ssbc/bench-ssb#5]
@staltz I'm opening this issue here to hopefully have a better way of measuring how changes to the ssb stack might affect manyverse. Is there a good way to run something like this easily on an android phone? And if so I'd be happy to run these benchmarks regularly as I already do for my normal x86 dev machine.

What sparked this: https://github.com/ssbc/ssb-keys/pull/59

**Comment by staltz** [comment]
Interesting! Yes, one way is through Termux (you should try that first), just install Termux, then inside it use `apt` to install git and node.js, then clone the repo and run it as normally. You might have some quirks to fix, and typing on the phone may be annoying.

The other way, which I think would be better, is if we setup a react native project inside this repo just to run the benchmarks. I've done that once for Mapeo Mobile, and it worked: https://github.com/digidem/mapeo-mobile/tree/9eab75ed7a603352818e9525a85399d413be18c6/benchmark

I could do this if I find the time, but if you'd like, I can guide you into the steps to get there.

**Comment by arj03** [comment]
I'll give it a go. Thanks for the pointers.

**Comment by staltz** [comment]
Note: in that link I think I used react-native-node, but that's been deprecated. nodejs-mobile is better. To get started, check the react native get started and the nodejs-mobile get started

**Comment by arj03** [comment]
I'm trying to run this using termux. Its pretty neat that you can just install a ssh server and then you remotely control the phone and install everything to run the tests. My only problem is that I can't get libsodium/sodium-native to compile properly. My phone is an arm64 and it doesn't seem as if there are prebuilds for that.

I tried https://github.com/luandro/sodium-native-android without any luck. 

What are you using in manyverse @staltz ?

**Comment by staltz** [comment]
Actually the latest version of sodium-native compiled correctly in Manyverse (or maybe it didn't and the whole thing fell back to libsodium-tweetnacl which caused a drop in performance?) so I don't think there's anything to do other than use the latest version. Sometimes I have also used https://github.com/staltz/sodium-native-no-prebuild which has no prebuild, so it actually builds with the correct host compiler (takes more time, but not too much time).

**Comment by arj03** [comment]
Yeah that is probably it. The problem is that it doesn't compile properly in termux for me. It tried both normal version and sodium-native-android that luando did. 

There is a newer version of libsodium 1.0.18 out with wasm support, so that might be something.

Anyway I'll see what I can come up with, was just wondering if there was some trick I didn't know about yet :-) It's been a while since I dabbled with C++ flags to a compiler ;-)

**Comment by arj03** [comment]
Aha, its actually wasm that fails to load, so that is why it is slow. Investigating :)

**Comment by arj03** [comment]
Seems to be [this](https://github.com/dominictarr/sodium-browserify/issues/5) :)

**Comment by arj03** [comment]
Also very interesting that wasm is only slightly slower than the c version on my laptop. 63  versus 59 seconds. Next up testing on phone :rocket:

**Comment by arj03** [comment]
Phone (Sony Xperia XA2) is 106 seconds by comparison. Interesting. This is testing validate btw.

**Comment by staltz** [comment]
@arj03 Hey, got any news on this issue? Do you think I can use ssb-server 15 with wasm on mobile?

**Comment by arj03** [comment]
@staltz yes it is running. I would recommended doing something like this to make sure wasm is loaded, as js is insanely slow. I wonder if some many verse users has run into this problem. 

https://github.com/ssbc/bench-ssb/blob/android-termux/android-wrapper.js

https://github.com/dominictarr/sodium-browserify/pull/6

**Comment by arj03** [comment]
With that merged I updated the instructions and should be ready to go.
